CREATE TABLE DEAN (
Dean_Id SMALLINT NOT NULL AUTO_INCREMENT,
PRIMARY KEY (Dean_Id),
CONSTRAINT fkDean_Id FOREIGN KEY (Dean_Id) REFERENCES Professor (Professor_Id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;